const actionTypes = {
  CHANGE_USER: 'CHANGE_USER',
  UPDATE_SCORE: 'UPDATE_SCORE',
  SET_SCORES: 'SET_SCORES',
  UPDATE_TOPLISTS: 'GET_TOPLISTS',
  UPDATE_RUNNING_LEVEL: 'UPDATE_RUNNING_LEVEL',
  UPDATE_SAVED: 'UPDATE_SAVED',
  TIME_RUNNING: 'TIME_RUNNING',
  UPDATE_RUNNING_STATUS: 'UPDATE_RUNNING_STATUS',
  SET_LEVELS_AMOUNT: 'SET_LEVELS_AMOUNT'
};

export default actionTypes;
